"""Jira exporter — creates issues from a spec tasks.yaml."""

from __future__ import annotations

import base64
import json
import os
from pathlib import Path
from typing import Any, Dict, List, Optional

import yaml


class JiraExporter:
    """Export spec task tracks to Jira as issues.

    Requires ``requests`` (included in ``corbell[jira]``).
    Credentials: ``CORBELL_JIRA_URL``, ``CORBELL_JIRA_EMAIL``,
    ``CORBELL_JIRA_API_TOKEN``, ``CORBELL_JIRA_PROJECT_KEY`` env vars
    or workspace config.

    Example::

        exporter = JiraExporter(
            url="https://mycompany.atlassian.net",
            email="eng@mycompany.com",
            api_token="ATATT...",
            project_key="ENG",
        )
        created = exporter.export_tasks("feature.tasks.yaml")
    """

    def __init__(
        self,
        url: Optional[str] = None,
        email: Optional[str] = None,
        api_token: Optional[str] = None,
        project_key: Optional[str] = None,
        issue_type: str = "Task",
    ):
        self.url = (url or os.environ.get("CORBELL_JIRA_URL", "")).rstrip("/")
        self.email = email or os.environ.get("CORBELL_JIRA_EMAIL", "")
        self.api_token = api_token or os.environ.get("CORBELL_JIRA_API_TOKEN", "")
        self.project_key = project_key or os.environ.get("CORBELL_JIRA_PROJECT_KEY", "")
        self.issue_type = issue_type

    # ------------------------------------------------------------------ #
    # Public API                                                           #
    # ------------------------------------------------------------------ #

    def export_tasks(self, tasks_yaml_path: Path | str) -> List[Dict[str, Any]]:
        """Create Jira issues from a tasks.yaml file.

        Args:
            tasks_yaml_path: Path to the ``.tasks.yaml`` generated by
                ``corbell spec decompose``.

        Returns:
            List of dicts with ``issue_key``, ``title``, and ``url`` per
            created issue.

        Raises:
            ImportError: If ``requests`` is not installed.
            ValueError: If credentials are not configured.
        """
        self._validate_credentials()

        try:
            import requests
        except ImportError:
            raise ImportError("requests is not installed. Run: pip install corbell[jira]")

        tasks_path = Path(tasks_yaml_path)
        data = yaml.safe_load(tasks_path.read_text(encoding="utf-8"))
        tracks = data.get("tracks", [])
        spec_title = data.get("title", "Feature")

        session = requests.Session()
        session.headers.update(self._auth_headers())
        session.headers["Content-Type"] = "application/json"

        created: List[Dict[str, Any]] = []

        for track in tracks:
            for task in track.get("tasks", []):
                title = f"[{spec_title}] {task.get('title', 'Task')}"
                description = self._build_description(task)

                payload = {
                    "fields": {
                        "project": {"key": self.project_key},
                        "summary": title,
                        "description": description,
                        "issuetype": {"name": self.issue_type},
                    }
                }

                resp = session.post(
                    f"{self.url}/rest/api/3/issue",
                    data=json.dumps(payload),
                    timeout=30,
                )
                resp.raise_for_status()
                result = resp.json()

                issue_key = result.get("key", "")
                created.append(
                    {
                        "issue_key": issue_key,
                        "title": title,
                        "url": f"{self.url}/browse/{issue_key}" if issue_key else "",
                    }
                )

        return created

    # ------------------------------------------------------------------ #
    # Internal helpers                                                     #
    # ------------------------------------------------------------------ #

    def _validate_credentials(self) -> None:
        missing = []
        if not self.url:
            missing.append("url (CORBELL_JIRA_URL)")
        if not self.email:
            missing.append("email (CORBELL_JIRA_EMAIL)")
        if not self.api_token:
            missing.append("api_token (CORBELL_JIRA_API_TOKEN)")
        if not self.project_key:
            missing.append("project_key (CORBELL_JIRA_PROJECT_KEY)")
        if missing:
            raise ValueError(
                f"Jira credentials not configured: {', '.join(missing)}.\n"
                "Set env vars or add 'integrations.jira.*' to workspace.yaml."
            )

    def _auth_headers(self) -> Dict[str, str]:
        token = base64.b64encode(f"{self.email}:{self.api_token}".encode()).decode()
        return {"Authorization": f"Basic {token}"}

    def _build_description(self, task: Dict[str, Any]) -> Dict[str, Any]:
        """Build an Atlassian Document Format description block."""
        content_nodes = []

        desc = task.get("description", "").strip()
        if desc:
            content_nodes.append(
                {
                    "type": "paragraph",
                    "content": [{"type": "text", "text": desc}],
                }
            )

        files = task.get("files_affected", [])
        if files:
            file_list = ", ".join(files)
            content_nodes.append(
                {
                    "type": "paragraph",
                    "content": [
                        {"type": "text", "text": "Files: ", "marks": [{"type": "strong"}]},
                        {"type": "text", "text": file_list},
                    ],
                }
            )

        if not content_nodes:
            content_nodes.append(
                {"type": "paragraph", "content": [{"type": "text", "text": " "}]}
            )

        return {"version": 1, "type": "doc", "content": content_nodes}
