"""Linear exporter — creates issues from a spec tasks.yaml."""

from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any, Dict, List, Optional

import yaml


class LinearExporter:
    """Export spec task tracks to Linear as issues.

    Requires ``requests`` (included in ``corbell[linear]``).
    Credentials: ``CORBELL_LINEAR_API_KEY``, ``CORBELL_LINEAR_TEAM_ID``,
    ``CORBELL_LINEAR_PROJECT_ID`` env vars or workspace config.
    """

    LINEAR_API = "https://api.linear.app/graphql"

    def __init__(
        self,
        api_key: Optional[str] = None,
        team_id: Optional[str] = None,
        project_id: Optional[str] = None,
    ):
        self.api_key = api_key or os.environ.get("CORBELL_LINEAR_API_KEY")
        self.team_id = team_id or os.environ.get("CORBELL_LINEAR_TEAM_ID")
        self.project_id = project_id or os.environ.get("CORBELL_LINEAR_PROJECT_ID")

    def export_tasks(self, tasks_yaml_path: Path | str) -> List[Dict[str, Any]]:
        """Create Linear issues from a tasks.yaml file.

        Args:
            tasks_yaml_path: Path to the ``.tasks.yaml`` generated by ``spec:decompose``.

        Returns:
            List of dicts with ``issue_id`` and ``title`` per created issue.

        Raises:
            ImportError: If ``requests`` is not installed.
            ValueError: If credentials are not configured.
        """
        if not self.api_key:
            raise ValueError(
                "Linear API key not configured. Set CORBELL_LINEAR_API_KEY env var "
                "or 'integrations.linear.api_key' in workspace.yaml."
            )
        if not self.team_id:
            raise ValueError("Linear team ID not configured. Set CORBELL_LINEAR_TEAM_ID env var.")

        try:
            import requests
        except ImportError:
            raise ImportError("requests is not installed. Run: pip install corbell[linear]")

        tasks_path = Path(tasks_yaml_path)
        data = yaml.safe_load(tasks_path.read_text(encoding="utf-8"))
        tracks = data.get("tracks", [])
        spec_title = data.get("title", "Feature")

        created: List[Dict[str, Any]] = []

        for track in tracks:
            track_label = track.get("name", "Task")
            for task in track.get("tasks", []):
                title = f"[{spec_title}] {task.get('title', 'Task')}"
                desc_parts = [task.get("description", "")]
                files = task.get("files_affected", [])
                if files:
                    desc_parts.append(f"\n**Files:** {', '.join(files)}")
                description = "\n".join(desc_parts)

                mutation = """
                mutation IssueCreate($input: IssueCreateInput!) {
                  issueCreate(input: $input) {
                    success
                    issue { id identifier title url }
                  }
                }
                """
                variables: Dict[str, Any] = {
                    "input": {
                        "title": title,
                        "description": description,
                        "teamId": self.team_id,
                    }
                }
                if self.project_id:
                    variables["input"]["projectId"] = self.project_id

                resp = requests.post(
                    self.LINEAR_API,
                    json={"query": mutation, "variables": variables},
                    headers={
                        "Authorization": self.api_key,
                        "Content-Type": "application/json",
                    },
                    timeout=30,
                )
                resp.raise_for_status()
                result = resp.json()
                issue = result.get("data", {}).get("issueCreate", {}).get("issue", {})
                if issue:
                    created.append(
                        {
                            "issue_id": issue.get("id", ""),
                            "identifier": issue.get("identifier", ""),
                            "title": issue.get("title", ""),
                            "url": issue.get("url", ""),
                        }
                    )

        return created
